version: '3.8'
services:
  app:
    build: .
    container_name: koppen-app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/koppen
    command: ["uvicorn", "koppen.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M

  db:
    image: postgres:16-alpine
    container_name: koppen-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=koppen
    ports:
      - "5432:5432"

volumes:
  postgres_data:
