version: '3.8'

services:
  app:
    image: cr.yandex/crpdcq8rd3suju9jjn8k/koppen:latest
    restart: unless-stopped
    ports:
      - "80:8000"
    environment:
      # - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/koppen
      - ENVIRONMENT=production
    # depends_on:
    #   - db

#     app:
#       build: . 
#       restart: unless-stopped
#       ports:
#         - "80:8000"
#       environment:
#         # - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/koppen
#         - ENVIRONMENT=production
# #   db:
#     image: postgres:16-alpine
#     restart: unless-stopped
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=${DB_PASSWORD}
#       - POSTGRES_DB=koppen
#     expose:
#       - "5432"

# volumes:
#   postgres_data:
