version: '3.8'
services:
  app:
    build: .
    container_name: koppen-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/koppen
    command: ["uvicorn", "koppen.main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: koppen-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=koppen
    ports:
      - "5432:5432"

volumes:
  postgres_data:
