"""First migration

Revision ID: 01
Revises: 
Create Date: 2025-06-28 14:07:26.728515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('powercurve',
    sa.Column('wind_speed_value_map', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('is_user', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('windfarm',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('windturbine',
    sa.Column('power_curve_id', sa.Integer(), nullable=True),
    sa.Column('hub_height', sa.Float(), nullable=False),
    sa.Column('turbine_type', sa.String(length=255), nullable=True),
    sa.Column('nominal_power', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['power_curve_id'], ['powercurve.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('windturbinefleet',
    sa.Column('wind_farm_id', sa.Integer(), nullable=True),
    sa.Column('wind_turbine_id', sa.Integer(), nullable=False),
    sa.Column('number_of_turbines', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wind_farm_id'], ['windfarm.id'], ),
    sa.ForeignKeyConstraint(['wind_turbine_id'], ['windturbine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('windturbinefleet')
    op.drop_table('windturbine')
    op.drop_table('windfarm')
    op.drop_table('user')
    op.drop_table('powercurve')
    op.drop_table('location')
    # ### end Alembic commands ###
