"""Add forecasts email recipients

Revision ID: 03
Revises: 46206b43f144
Create Date: 2025-07-10 23:53:21.311131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03'
down_revision = '46206b43f144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast', sa.Column('recipients', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast', 'recipients')
    # ### end Alembic commands ###
