"""Update forecast model

Revision ID: 04
Revises: 03
Create Date: 2025-07-13 15:39:28.360561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04'
down_revision = '03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('forecast', sa.Column('granularity', sa.Enum('minutes_60', 'minutes_30', 'minutes_15', name='granularityenum'), nullable=False))
    op.add_column('forecast', sa.Column('horizon', sa.Enum('hour_3', 'hour_24', 'hour_48', 'hour_120', name='horizonenum'), nullable=False))
    op.add_column('forecast', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('forecast', sa.Column('forecast_frequency', sa.Enum('daily', 'hourly', name='forecastfrequencyenum'), nullable=False))
    op.add_column('forecast', sa.Column('enable', sa.Boolean(), nullable=True))
    op.drop_column('forecast', 'hourly_minute')
    op.drop_column('forecast', 'daily_time')
    op.drop_column('forecast', 'time_resolution')
    op.drop_column('forecast', 'repeat_hourly')
    op.drop_column('forecast', 'repeat_daily')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast', sa.Column('repeat_daily', sa.BOOLEAN(), nullable=True))
    op.add_column('forecast', sa.Column('repeat_hourly', sa.BOOLEAN(), nullable=True))
    op.add_column('forecast', sa.Column('time_resolution', sa.VARCHAR(length=6), nullable=False))
    op.add_column('forecast', sa.Column('daily_time', sa.TIME(), nullable=True))
    op.add_column('forecast', sa.Column('hourly_minute', sa.INTEGER(), nullable=True))
    op.drop_column('forecast', 'enable')
    op.drop_column('forecast', 'forecast_frequency')
    op.drop_column('forecast', 'start_time')
    op.drop_column('forecast', 'horizon')
    op.drop_column('forecast', 'granularity')
    op.drop_column('forecast', 'name')
    # ### end Alembic commands ###
