"""Add forecast history model

Revision ID: 05
Revises: 04
Create Date: 2025-07-13 16:56:44.161282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05'
down_revision = '04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasthistory',
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('wind_farm_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('csv_data', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecast.id'], ),
    sa.ForeignKeyConstraint(['wind_farm_id'], ['windfarm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecasthistory')
    # ### end Alembic commands ###
