"""Add forecast history modell

Revision ID: 06
Revises: 05
Create Date: 2025-07-13 16:59:49.123801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06'
down_revision = '05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
