"""Add forecast model and link to wind farm

Revision ID: 46206b43f144
Revises: 01
Create Date: 2025-07-01 01:52:40.575235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46206b43f144'
down_revision = '01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast',
    sa.Column('time_resolution', sa.Enum('minute', 'hour', 'day', name='timeresolutionenum'), nullable=False),
    sa.Column('wind_farm_id', sa.Integer(), nullable=False),
    sa.Column('repeat_daily', sa.Boolean(), nullable=True),
    sa.Column('daily_time', sa.Time(), nullable=True),
    sa.Column('repeat_hourly', sa.Boolean(), nullable=True),
    sa.Column('hourly_minute', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wind_farm_id'], ['windfarm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecast')
    # ### end Alembic commands ###
