name: Tests & Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          export PATH="/root/.cargo/bin:$PATH"
          
      - name: Install dependencies
        run: |
          uv pip install --system -e ".[test]"
          uv pip install --system ruff pytest pytest-asyncio httpx
          
      - name: Run Ruff linting
        run: |
          uv run ruff check .
          uv run ruff format --check .
          
      - name: Run tests
        run: |
          uv run pytest tests/ -v
